### ISSUE TITLE
Error when asked to split or create new file

### ISSUE THREAD

**Issue by JoeyMeijers** [kailichou/SplitExcelbyColumnValue#2]
Hi Kailichou, 

Thank you for helping me on YouTube!
I encounter another issue when the script asks me if I want to split the file in into sheets of a new file.

Traceback (most recent call last):
  File "split.py", line 54, in <module>
    sendTofile(cols)
  File "split.py", line 26, in sendTofile
    df[df[colpick]==i].to_excel("{}/{}.xlsx".format(pth, i), sheet_name=i, index=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 2175, in to_excel
    formatter.write(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/formats/excel.py", line 730, in write
    writer.write_cells(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/io/excel/_xlsxwriter.py", line 206, in write_cells
    wks = self.book.add_worksheet(sheet_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xlsxwriter/workbook.py", line 180, in add_worksheet
    return self._add_sheet(name, worksheet_class=worksheet_class)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xlsxwriter/workbook.py", line 729, in _add_sheet
    name = self._check_sheetname(name, isinstance(worksheet, Chartsheet))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/xlsxwriter/workbook.py", line 777, in _check_sheetname
    if len(sheetname) > 31:
TypeError: object of type 'float' has no len()

**Comment by kailichou** [comment]
You can change line 26
```
sheet_name=str(i)
```

**Comment by JoeyMeijers** [comment]
it works! Thank you. 
can't wait to see more from you!
